# Copyright 2012. All Rights Reserved.

AREA = {
    'outside': False,
    'paths': [
        '12 w;3 n;village', 'nw', 'nw', 'open south door;s',
        'open north door;n;w', 'open south door;s', 'w',
        'e;open north door;n;w', 'open southwest door;sw',
        'ne;open west door;w', 'open east door;e;nw', 'open northwest door;nw',
        'se;open west door;w', 'n', '2 s',
        'n;open east door;e;se;e;open north door;n', 'open west door;w',
        'open east door;e;open east door;e',
        'open west door;w;open north door;n',
        'open west door;w', 'open east door;2 e', 'n',
        's;w;open south door;s;open south door;s;e;2 se',
        'fields;3 s;12 e',
        ],
    'npcs': {
        #"Lars, the head farmhand of Denulf's farm": {'id': 'lars', 'size': 33, 'moves': False},
        #'Denulf the farmer, defending his properties': {'id': 'denulf', 'size': 18, 'moves': False},
        #'Eithne, a panic-stricken farmer woman': {'id': 'eithne', 'size': 14, 'moves': False},
        "Gullan, the maid of Denulf's farm": {'id': 'gullan', 'size': 14, 'moves': False},
        'A big black rat': {'id': 'rat', 'size': 4, 'moves': False},
        'A black bull with a ring in its nose': {'id': 'bull', 'size': 11, 'moves': False},
        'A black-brindled white cow': {'id': 'cow', 'size': 10, 'moves': False},
        'A brown rooster with green tail feathers': {'id': 'rooster', 'size': 5, 'moves': False},
        'A dirty boy running around in circles': {'id': 'boy', 'size': 16, 'moves': False},
        'A dirty girl playing with her toys': {'id': 'girl', 'size': 5, 'moves': False},
        'A dirty girl screaming for mommy': {'id': 'girl', 'size': 5, 'moves': False},
        'A dirty girl turning the room into a mess': {'id': 'girl', 'size': 5, 'moves': False},
        'A farmer carrying various farming tools': {'id': 'farmer', 'size': 14, 'moves': False},
        'A farmer woman with dark circles under her eyes': {'id': 'woman', 'size': 14, 'moves': False},
        'A fat boy playing with his toys': {'id': 'boy', 'size': 5, 'moves': False},
        'A fat boy screaming for mommy': {'id': 'boy', 'size': 5, 'moves': False},
        'A fat boy turning the room into a mess': {'id': 'boy', 'size': 5, 'moves': False},
        'A fat girl screaming for mommy': {'id': 'girl', 'size': 5, 'moves': False},
        'A fat girl turning the room into a mess': {'id': 'girl', 'size': 5, 'moves': False},
        'A fat pig, grubbing around in the sty': {'id': 'pig', 'size': 5, 'moves': False},
        'A gray sheep-dog with floppy ears': {'id': 'dog', 'size': 20, 'moves': False},
        'A large jovial farmer woman': {'id': 'woman', 'size': 14, 'moves': False},
        'A long-haired black cat with yellow eyes': {'id': 'cat', 'size': 5, 'moves': False},
        'A red-nosed farmer, holding a bottle': {'id': 'farmer', 'size': 14, 'moves': False},
        'A shabby white and black cat with long whiskers': {'id': 'cat', 'size': 5, 'moves': False},
        'A short-haired white cat with green eyes': {'id': 'cat', 'size': 5, 'moves': False},
        'A skinny boy playing with his toys': {'id': 'boy', 'size': 5, 'moves': False},
        'A skinny boy screaming for mommy': {'id': 'boy', 'size': 5, 'moves': False},
        'A skinny girl running around in circles': {'id': 'girl', 'size': 5, 'moves': False},
        'A skinny white cat with yellow eyes': {'id': 'cat', 'size': 5, 'moves': False},
        'A small boy turning the room into a mess': {'id': 'boy', 'size': 5, 'moves': False},
        'A small girl running around in circles': {'id': 'girl', 'size': 5, 'moves': False},
        'A small girl screaming for mommy': {'id': 'girl', 'size': 5, 'moves': False},
        'A small girl turning the room into a mess': {'id': 'girl', 'size': 5, 'moves': False},
        'A small yellow chicken': {'id': 'hen', 'size': 5, 'moves': False},
        'A speckled hen': {'id': 'hen', 'size': 5, 'moves': False},
        'A spotted pig, sniffing the stable odor': {'id': 'pig', 'size': 5, 'moves': False},
        'A sturdy brown working horse': {'id': 'horse', 'size': 11, 'moves': False},
        'A white goose waddling around': {'id': 'goose', 'size': 5, 'moves': False},
        'An obnoxious boy running around in circles': {'id': 'boy', 'size': 5, 'moves': False},
        'An obnoxious boy screaming for mommy': {'id': 'boy', 'size': 5, 'moves': False},
        'The millers wife Geena, keeping everything neat and clean': {'id': 'geena', 'size': 14, 'moves': False},
        'Weohstan the hard working village miller': {'id': 'weohstan', 'size': 18, 'moves': False},
      },
    }
