# Copyright 2012. All Rights Reserved.

AREA = {
    'outside': False,
    'paths': [
        '15 w;s;sw;w;nw;2 n;enter;d;w;n;w;d',
        'u;e;n;break',
        'get diamond;n',
        'e;s;e',
        '2 w;break',
        'get diamond;2 s;se;ne',
        'se',
        'nw;n',
        'n',
        'n',
        '3 s;sw;nw;2 w;n;d',
        'n;open',
        's;u;search carpets;se',
        'nw;s;3 e;u;out;2 s;se;e;ne;n;15 e',
        ],
    'npcs': {
        'A large mushroom pulsing with light.': {'id': 'mushroom', 'size': 12},
        'A dread Minitaur.': {'id': 'minitaur', 'size': 15},
        'A ropeless...Like a roper but without the ropes.': {'id': 'ropeless', 'size': 14},
        'A Uniduck': {'id': 'uniduck', 'size': 18},
        'Arghh, the miniature fire giant.': {'id': 'arghh', 'size': 15},
        'Jethro, the miniature hill giant.': {'id': 'jethro', 'size': 15},
        'Rocky, the miniature stone giant.': {'id': 'rocky', 'size': 15},
        'Glacon, the miniature frost giant.': {'id': 'glacon', 'size': 15},
        'A large dark grey porpoise.': {'id': 'porpoise', 'size': 15},
        'A gelatinous disc': {'id': 'disc', 'size': 18},
        'A large brown and white cow.': {'id': 'cow', 'size': 5},
        'A large brown Llama.': {'id': 'llama', 'size': 10},
        'Zando the magician.': {'id': 'zando', 'size': 45},
        'A short, hairy, ugly goblin.': {'id': 'goblin', 'size': 32},
        'Gunter, leader of the ragtag fugitive goblins': {'id': 'gunter', 'size': 32},
        'A giant Cretin...like an Ettin but not as smart': {'id': 'cretin', 'size': 32},
        #'An eye of the shallows.': {'id': 'beholder', 'size': 16},
        },
    }
